export const vfs: any = {
    'Amiri-Bold.ttf': 'AAEAAAAPAIAAAwBwR0RFRnZzbVwABNCkAAADCEdQT1Mm7XHNAATTrAAA71JHU1VCNapvmwAFwwAAAIwmT1MvMp+rc3oAAAF4AAAAYGNtYXDvFNVKAABoNAAABLZnYXNwAAAAEAAE0JwAAAAIZ2x5ZoNj2tgAANNUAAPx1WhlYWTOpycqAAAA/AAAADZoaGVhL8YaqgAAATQAAAAkaG10eKvSeHwAAAHYAABmXGxvY2EyDleWAABs9AAAZmBtYXhwGfgGxQAAAVgAAAAgbmFtZbe69X0ABMUsAAALUHBvc3T+AwAyAATQfAAAACBwcmVwaAaMhQAAbOwAAAAHAAEAAAABAIMFPZeOXw889QADA+gAAAAAyAoxsQAAAAB8JbCA/kH8cy0eBx8AAQAGAAIAAQAAAAAAAQAABGT9hgAALMP+QdLiLR4D6AAAAAAAAAAAAAAAAAAAGZcAAQAAGZc',
    "Amiri-Regular.ttf": "AAEAAAAPAIAAAwBwR0RFRoA3oIQABS0gAAADQEdQT1OuDBunAAUwYAAA1yhHU1VCKX3XTAAGB4gAAIyET1MvMp5/dp8AAAF4AAAAYGNtYXDwK+OqAABqhAAAESJnYXNwAAAAEAAFLRgAAAAIZ2x5ZvJz3KQAAOSMAAQ9AWhlYWTOXCcrAAAA/AAAADZoaGVhL3wbfgAAATQAAAAkaG10eDnUxFUAAAHYAABoqmxvY2E4yrZUAAB7sAAAaNxtYXhwGpcGhAAAAVgAAAAgbmFtZb0S9/cABSGQAAALaHBvc3T+..."
};

export const fonts = {
  Amiri: {
    normal: 'Amiri-Regular.ttf',
    bold: 'Amiri-Bold.ttf',
    italics: 'Amiri-Regular.ttf',
    bolditalics: 'Amiri-Bold.ttf'
  }
};